version: 1.0.{build}

cache:
  - packages -> **\packages.config  # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified
  - '%LocalAppData%\NuGet\Cache'

image: Visual Studio 2015
  
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}-rc'
  
before_build:
  - nuget restore
  
platform: Any CPU

configuration: Release

artifacts:
  - path: RutaHttpModule\bin\$(configuration)\*.dll
  - path: web-user.config
  - path: web-runner.config
  - path: InstallRutaModule.ps1
