cache:
  - packages -> **\packages.config  # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified
  - '%LocalAppData%\NuGet\Cache'

image: Visual Studio 2015
  
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: '1.0.{build}'
  assembly_file_version: '1.0.{build}'
  assembly_informational_version: '1.0.{build}-rc'
  
before_build:
  - nuget restore
  
platform: Any CPU

configuration: Release

test:
  assemblies:
    - RutaHttpModuleTest.dll